import './globals.css'
import type { Metadata } from 'next'
//import { Inter } from 'next/font/google'
import DefaultNavbar from './components/Navbar'
import FlowbiteContext from './components/FlowbiteContext'

//const inter = Inter({ subsets: ['latin'] }) // className={inter.className}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-200 h-screen flex flex-col" >
        <DefaultNavbar />
        <FlowbiteContext>{children}</FlowbiteContext>
      </body>
    </html>
  )
}
